require("__khaostransportgroup__.prototypes.compat.aai-vehicles-ironclad-final-fixes")
require("__khaostransportgroup__.prototypes.compat.diesel-locomotive-final-fixes")
require("__khaostransportgroup__.prototypes.compat.electric-train-final-fixes")
require("__khaostransportgroup__.prototypes.compat.pyanodons-final-fixes")
require("__khaostransportgroup__.prototypes.compat.realistic-electric-trains-final-fixes")
require("__khaostransportgroup__.prototypes.compat.rubia-final-fixes")
